import type { Metadata } from "next";
import Link from "next/link";
import { CalendarDays, CheckCircle2 } from "lucide-react";
import { PublicFooter } from "@/components/PublicFooter";
import { PublicHeader } from "@/components/PublicHeader";

export const metadata: Metadata = { title: "Changelog", description: "A dated record of meaningful IR35Careers product changes." };
const releases = [
  { date: "20 August 2026", title: "Open public beta", items: ["Public signup remains open without a waitlist or invitation code", "Beta status is visible across the website, installed app and service emails", "Clear beta expectations, known boundaries and feedback route", "Prepared waitlist notice rewritten as a beta invitation and kept behind explicit send approval"] },
  { date: "20 August 2026", title: "Evidence-led contract filters", items: ["Seniority groups match explicit wording in the role title", "Rate-basis filtering separates daily, hourly and annual/FTC advertisements", "Sponsorship filtering requires positive wording and never treats an unknown listing as unavailable", "Saved alerts preserve the advanced filters after additive migration 012"] },
  { date: "20 August 2026", title: "Faster contract search", items: ["Initial results reduced to twelve focused cards with the complete catalogue retained through pagination", "Contract results render before slower facet aggregation finishes", "Facet counts load in the background and remain cached by the non-toggle search filters", "Phone, tablet and desktop regression coverage deliberately stalls facets to prove results stay responsive"] },
  { date: "20 August 2026", title: "Mobile, messaging and disclosure parity", items: ["Dedicated installable mobile workspace with browser install and live readiness states", "Offline recovery remains explicit about live contract freshness", "Recruiter email, WhatsApp and SMS surfaces report their real production connection state", "Public responsible-disclosure page and machine-readable security.txt policy", "Automated reduced-motion, responsive-overflow and accessibility coverage"] },
  { date: "20 August 2026", title: "Automated release gates", items: ["Vercel production builds now require type, lint, unit and domain checks", "GitHub runs the optimized build with exact locked dependencies", "Full Playwright and axe journeys run on phone, tablet and desktop", "Superseded branch runs cancel automatically; failure traces are retained for seven days"] },
  { date: "20 August 2026", title: "Stable contract loading states", items: ["Five-card search skeleton keeps the result column stable on first load", "Navigation and page heading remain visible through route hydration", "Shared actionable empty and error panels preserve filters", "Contract-detail skeleton and retry boundary prevent blank transitions on cold pages"] },
  { date: "20 August 2026", title: "Public contract feed health", items: ["Cached per-source active-contract counts and latest observation time", "Fresh, delayed, stale and unavailable states without exposing provider logs or credentials", "Daily refresh, cross-source duplicate reduction and ten-day expiry explained", "Health loads independently so filtering remains responsive"] },
  { date: "20 August 2026", title: "Safer private CV uploads", items: ["PDF and DOCX signatures checked before profile storage", "Active PDF features, Word macros and embedded objects rejected", "DOCX entry-count, path and expansion limits", "Failed profile saves roll back the new file; owner-scoped replacement cleanup runs only after the new reference is saved"] },
  { date: "20 August 2026", title: "Transparent IR35 evidence", items: ["Advertiser-stated, arrangement-derived, source/review and unconfirmed provenance states", "Exact matched IR35 wording shown when available", "Latest evidence-check date and confidence visible on every contract detail", "Conflicts and non-reproducible labels prompt contractors to verify the original advert and SDS"] },
  { date: "20 August 2026", title: "Reliable account recovery", items: ["Password-reset mode keeps the account email field visible", "Password input removed from reset requests", "Sign-in, sign-up and recovery states verified on phone, tablet and desktop", "Neutral sign-in errors continue to avoid exposing whether an account exists"] },
  { date: "20 August 2026", title: "Faster contract details", items: ["Public job-detail pages cached for one minute", "Metadata and page rendering share one deduplicated contract lookup", "Fresh detail generated automatically after the short cache window", "No caching added to private account or application data"] },
  { date: "20 August 2026", title: "Explainable contract matching", items: ["Inspect the skills, rate, IR35 and workplace points behind a match", "Case-insensitive comparison for canonical skill names", "Profile skills absent from structured listing tags shown as gaps", "Percentage withheld when there is no structured skill overlap instead of showing a misleading result"] },
  { date: "20 August 2026", title: "Curated alert previews", items: ["On-demand live match preview for every saved search", "Request cancellation and stale-response protection when switching alerts", "Responsive loading, empty, retry and delete-confirmation states", "Visible email-provider gate so an in-product preview is never presented as a delivered alert"] },
  { date: "20 August 2026", title: "Reviewable application receipts", items: ["Immutable dry-run snapshot of the approved CV, cover letter and screening answers", "Expandable exact-answer review after receipt creation", "Accuracy or change-needed feedback stored with the application", "Clear separation between a preparation receipt and an ATS submission confirmation"] },
  { date: "20 August 2026", title: "Faster public browsing", items: ["Server-rendered featured contracts with a one-minute freshness window", "Removed eager account and workspace downloads from public pages", "Kept sign-in and sign-up available without loading their code before it is needed", "Reduced the pricing-page unused JavaScript measured during release checks"] },
  { date: "20 August 2026", title: "Safe subscription foundation", items: ["Hosted Stripe Checkout and self-service customer portal behind a complete provider gate", "Signed webhook validation with a private idempotent event ledger", "Live-only entitlement granting so test payments never unlock Pro", "Billing, cancellation, cooling-off and refund policy", "Account deletion cancels the linked subscription before erasing local data"] },
  { date: "20 August 2026", title: "Contract-search analytics", items: ["Private application funnel and outcome rates", "Eight-week preparation and response activity", "IR35, workplace and source breakdowns", "Unread, stale-role and networking follow-up signals", "CSV export that excludes CV and message content"] },
  { date: "20 August 2026", title: "Developer connections and referrals", items: ["Protocol-tested read-only MCP server for public contract discovery", "Public provider-connection dashboard with secret-safe state reporting", "Account-owned relationship map and follow-up queue", "Role-linked referral drafts with explicit review and manual sending", "Networking privacy and acceptable-use disclosures"] },
  { date: "20 August 2026", title: "Brand, trust and account-control release", items: ["New original IR35Careers path mark and complete app/social icon set", "Separate sign-in and sign-up actions plus password recovery", "Account-data export and user-confirmed permanent deletion", "Installable mobile web app and offline recovery", "Privacy, cookie, terms, accessibility, AI, security and listing transparency pages", "Faster, source-aware contract filtering and corrected TBC/day-rate handling"] },
  { date: "19 August 2026", title: "Contractor preparation workspace", items: ["Truth-preserving CV analysis with role score and keyword gaps", "Side-by-side suggestion approval, immutable versions and PDF/DOCX export", "Role-grounded cover letter and reviewed screening answers", "Dry-run application receipt, tracker, linked inbox and automation rules"] },
  { date: "19 August 2026", title: "Public contract discovery", items: ["Responsive UK contract search with IR35 evidence, rates and workplace labels", "Original-source handoff, saved roles and alert definitions", "IR35 status checker and take-home calculator"] },
];

export default function ChangelogPage() {
  return <div className="min-h-screen bg-slate-50"><PublicHeader /><main className="ir35-container py-12 sm:py-16"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-brand-700">Product history</p><h1 className="mt-3 text-4xl font-bold tracking-[-0.04em] text-slate-950 sm:text-5xl">Changelog</h1><p className="mt-5 text-base leading-7 text-slate-600">A public record of shipped capabilities and the safety boundaries that matter to contractors.</p></div><div className="mt-10 max-w-4xl space-y-6">{releases.map((release)=><article key={release.title} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-card sm:p-8"><p className="flex items-center gap-2 text-xs font-bold text-brand-700"><CalendarDays size={14} />{release.date}</p><h2 className="mt-3 text-2xl font-bold tracking-tight text-slate-950">{release.title}</h2><ul className="mt-5 grid gap-3 sm:grid-cols-2">{release.items.map((item)=><li key={item} className="flex items-start gap-2 text-sm leading-6 text-slate-600"><CheckCircle2 size={16} className="mt-1 shrink-0 text-brand-700" />{item}</li>)}</ul></article>)}</div><p className="mt-8 text-sm text-slate-600">For implementation detail, safety questions or corrections, <Link href="/contact" className="font-bold text-brand-700 underline">contact IR35Careers</Link>.</p></main><PublicFooter /></div>;
}
