import type { Metadata } from "next";
import Link from "next/link";
import { AlertTriangle, CheckCircle2, ShieldCheck } from "lucide-react";
import { PublicFooter } from "@/components/PublicFooter";
import { PublicHeader } from "@/components/PublicHeader";
import { buttonClassName } from "@/components/ui/button";

export const metadata: Metadata = {
  title: "Report a Security Issue",
  description: "Good-faith vulnerability reporting rules for IR35Careers. No paid bug-bounty programme is currently offered.",
};

export default function BugBountyPage() {
  return <div className="min-h-screen bg-slate-50 text-slate-950"><PublicHeader /><main className="ir35-container py-12 sm:py-16"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-brand-700">Responsible disclosure</p><h1 className="mt-3 text-4xl font-bold tracking-[-0.05em] sm:text-5xl">Report a security issue safely.</h1><p className="mt-5 text-base leading-7 text-slate-600">IR35Careers welcomes reproducible, good-faith vulnerability reports. There is not currently a paid bug-bounty programme, and this page does not promise a reward.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/contact" className={buttonClassName({ size: "lg" })}>Start a security disclosure</Link><Link href="/security" className={buttonClassName({ variant: "secondary", size: "lg" })}>Read security controls</Link></div></div><section className="mt-10 grid gap-5 lg:grid-cols-3"><article className="rounded-3xl border border-emerald-200 bg-emerald-50 p-6"><CheckCircle2 className="text-emerald-800" aria-hidden="true" /><h2 className="mt-4 text-lg font-bold text-emerald-950">Helpful report</h2><p className="mt-2 text-sm leading-6 text-emerald-900">Include the affected URL, likely impact, safe reproduction steps and a way to contact you. Begin the contact message with “Security disclosure”.</p></article><article className="rounded-3xl border border-amber-200 bg-amber-50 p-6"><AlertTriangle className="text-amber-800" aria-hidden="true" /><h2 className="mt-4 text-lg font-bold text-amber-950">Stop at user data</h2><p className="mt-2 text-sm leading-6 text-amber-900">Do not access another person&apos;s account, retain personal information, degrade the service, send spam, upload malware or test third-party providers.</p></article><article className="rounded-3xl border border-slate-200 bg-white p-6"><ShieldCheck className="text-brand-700" aria-hidden="true" /><h2 className="mt-4 text-lg font-bold">Coordinated response</h2><p className="mt-2 text-sm leading-6 text-slate-600">A reproducible report is triaged, relevant evidence is preserved and disclosure is coordinated until a proportionate fix protects users.</p></article></section><section className="mt-8 rounded-3xl border border-slate-200 bg-white p-6 sm:p-8"><h2 className="text-2xl font-bold">Machine-readable policy</h2><p className="mt-3 text-sm leading-6 text-slate-600">Security tooling can discover the reporting route at <a href="/.well-known/security.txt" className="font-bold text-brand-700 underline">/.well-known/security.txt</a>. It contains no credentials or private contact data.</p></section></main><PublicFooter /></div>;
}
