"use client";

import { useState } from "react";
import { Building2, CheckCircle2, FileText, IdCard, ListChecks, ShieldCheck, UserRound } from "lucide-react";
import { WorkspacePage } from "@/components/workspace/WorkspacePage";
import { updateWorkspace, useWorkspaceState } from "@/lib/workspace/store";
import type { ContractorProfile as ContractorProfileType } from "@/lib/workspace/types";

function Field({ label, value, onChange, type = "text", placeholder }: { label: string; value: string; onChange: (value: string) => void; type?: string; placeholder?: string }) {
  return <label className="text-sm font-semibold text-slate-800">{label}<input type={type} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="ir35-focus mt-2 min-h-11 w-full rounded-xl border border-slate-300 bg-slate-50 px-3 text-sm font-normal text-slate-900" /></label>;
}

function YesNoField({ label, value, onChange }: { label: string; value: boolean | null | undefined; onChange: (value: boolean | null) => void }) {
  return <label className="text-sm font-semibold text-slate-800">{label}<select value={value === true ? "yes" : value === false ? "no" : ""} onChange={(event) => onChange(event.target.value === "yes" ? true : event.target.value === "no" ? false : null)} className="ir35-focus mt-2 min-h-11 w-full rounded-xl border border-slate-300 bg-slate-50 px-3 text-sm font-normal text-slate-900"><option value="">Choose an answer</option><option value="yes">Yes</option><option value="no">No</option></select></label>;
}

export function ContractorProfile() {
  const workspace = useWorkspaceState();
  const [profile, setProfile] = useState<ContractorProfileType>(workspace.profile);
  const [saved, setSaved] = useState(false);
  const set = <K extends keyof ContractorProfileType>(key: K, value: ContractorProfileType[K]) => setProfile((current) => ({ ...current, [key]: value }));
  const save = () => { updateWorkspace((current) => ({ ...current, profile, inbox: { ...current.inbox, forwardingEmail: profile.forwardingEmail } })); setSaved(true); };

  const applicationDefaults = [profile.fullName, profile.email, profile.phone, profile.addressLine1, profile.city, profile.postcode, profile.country, profile.defaultCvLabel, profile.availability, profile.educationInstitution, profile.educationQualification, profile.isOver18, profile.canWorkInPerson, profile.canRelocate, profile.canStartImmediately, profile.hasTransportation, profile.needsAccommodation, profile.workedForCompanyBefore, profile.hasGovernmentClearance, profile.hasGovernmentTies];
  const completed = applicationDefaults.filter((value) => value !== "" && value !== null && value !== undefined).length;
  const completeness = Math.round((completed / applicationDefaults.length) * 100);

  return (
    <WorkspacePage eyebrow="Contractor profile" title="Your evidence and application defaults" description="Keep reusable facts in one place so every role-specific packet starts from accurate information. Sensitive fields stay in this browser during local preview.">
      <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]">
        <div className="space-y-6">
          <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-card sm:p-6"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-brand-50 text-brand-700"><UserRound size={20} /></span><div><h2 className="font-semibold">Personal details</h2><p className="text-sm text-slate-600">Used only in application materials you approve.</p></div></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Full name" value={profile.fullName} onChange={(value) => set("fullName", value)} /><Field label="Email" type="email" value={profile.email} onChange={(value) => set("email", value)} /><Field label="Phone" value={profile.phone} onChange={(value) => set("phone", value)} /><Field label="Location" value={profile.location} onChange={(value) => set("location", value)} /><Field label="LinkedIn URL" type="url" value={profile.linkedInUrl} onChange={(value) => set("linkedInUrl", value)} /><Field label="Portfolio URL" type="url" value={profile.portfolioUrl} onChange={(value) => set("portfolioUrl", value)} /></div></section>

          <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-card sm:p-6"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-blue-50 text-blue-700"><IdCard size={20} /></span><div><h2 className="font-semibold">Work authorisation and availability</h2><p className="text-sm text-slate-600">Never inferred from a CV or nationality.</p></div></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-800">Right to work in the UK<select value={profile.rightToWork} onChange={(event) => set("rightToWork", event.target.value as ContractorProfileType["rightToWork"])} className="ir35-focus mt-2 min-h-11 w-full rounded-xl border border-slate-300 bg-slate-50 px-3 text-sm font-normal"><option value="yes">Yes</option><option value="needs_sponsorship">Requires sponsorship</option><option value="no">No</option><option value="prefer_not_to_say">Prefer not to say</option></select></label><Field label="Availability" value={profile.availability} onChange={(value) => set("availability", value)} placeholder="e.g. Within two weeks" /><Field label="Notice period" value={profile.noticePeriod} onChange={(value) => set("noticePeriod", value)} /><Field label="Security clearance" value={profile.clearance} onChange={(value) => set("clearance", value)} placeholder="Do not claim a clearance you do not hold" /></div></section>

          <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-card sm:p-6"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-700"><ListChecks size={20} /></span><div><h2 className="font-semibold">One-click application defaults</h2><p className="text-sm text-slate-600">Add these once so supported employer forms can be completed without asking the same questions again.</p></div></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Address line 1" value={profile.addressLine1 ?? ""} onChange={(value) => set("addressLine1", value)} /><Field label="Town or city" value={profile.city ?? ""} onChange={(value) => set("city", value)} /><Field label="County or region" value={profile.county ?? ""} onChange={(value) => set("county", value)} /><Field label="Postcode" value={profile.postcode ?? ""} onChange={(value) => set("postcode", value)} /><Field label="Country" value={profile.country ?? ""} onChange={(value) => set("country", value)} /><YesNoField label="Are you 18 or over?" value={profile.isOver18} onChange={(value) => set("isOver18", value)} /><YesNoField label="Can you work in person?" value={profile.canWorkInPerson} onChange={(value) => set("canWorkInPerson", value)} /><YesNoField label="Can you relocate?" value={profile.canRelocate} onChange={(value) => set("canRelocate", value)} /><YesNoField label="Can you start immediately?" value={profile.canStartImmediately} onChange={(value) => set("canStartImmediately", value)} /><YesNoField label="Do you have reliable transport?" value={profile.hasTransportation} onChange={(value) => set("hasTransportation", value)} /><YesNoField label="Do you need a workplace accommodation?" value={profile.needsAccommodation} onChange={(value) => set("needsAccommodation", value)} /><YesNoField label="Have you worked for this company before?" value={profile.workedForCompanyBefore} onChange={(value) => set("workedForCompanyBefore", value)} /><YesNoField label="Do you hold government security clearance?" value={profile.hasGovernmentClearance} onChange={(value) => set("hasGovernmentClearance", value)} /><YesNoField label="Do you have government ties to declare?" value={profile.hasGovernmentTies} onChange={(value) => set("hasGovernmentTies", value)} /><Field label="Education institution" value={profile.educationInstitution ?? ""} onChange={(value) => set("educationInstitution", value)} /><Field label="Qualification" value={profile.educationQualification ?? ""} onChange={(value) => set("educationQualification", value)} /></div></section>

          <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-card sm:p-6"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-violet-50 text-violet-700"><Building2 size={20} /></span><div><h2 className="font-semibold">Limited company details</h2><p className="text-sm text-slate-600">Optional details for engagements where they are relevant.</p></div></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Company name" value={profile.limitedCompanyName} onChange={(value) => set("limitedCompanyName", value)} /><Field label="Companies House number" value={profile.companyNumber} onChange={(value) => set("companyNumber", value)} /><label className="flex min-h-12 cursor-pointer items-center gap-3 rounded-xl border border-slate-200 px-4 text-sm font-semibold"><input type="checkbox" checked={profile.vatRegistered} onChange={(event) => set("vatRegistered", event.target.checked)} className="h-5 w-5 accent-emerald-700" /> VAT registered</label></div></section>

          <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-card sm:p-6"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-amber-50 text-amber-700"><FileText size={20} /></span><div><h2 className="font-semibold">Documents and inbox</h2><p className="text-sm text-slate-600">Choose reusable labels and forwarding preferences.</p></div></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Default CV label" value={profile.defaultCvLabel} onChange={(value) => set("defaultCvLabel", value)} /><Field label="Forward recruiter messages to" type="email" value={profile.forwardingEmail} onChange={(value) => set("forwardingEmail", value)} /></div></section>

          <div className="flex items-center gap-4"><button type="button" onClick={save} className="ir35-focus inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-brand-600 px-6 text-sm font-bold text-white hover:bg-brand-700"><CheckCircle2 size={17} /> Save profile</button>{saved && <p role="status" className="text-sm font-semibold text-emerald-700">Profile saved locally.</p>}</div>
        </div>

        <aside className="space-y-5 xl:sticky xl:top-24 xl:h-max"><section className="rounded-3xl border border-slate-200 bg-white p-5 text-center shadow-card"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-slate-950 text-xl font-bold text-white">{profile.fullName.trim().charAt(0) || "C"}</div><h2 className="mt-4 font-semibold text-slate-950">{profile.fullName || "Your profile"}</h2><p className="mt-1 text-sm text-slate-500">UK contractor workspace</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-brand-600 transition-[width]" style={{ width: `${completeness}%` }} /></div><p className="mt-2 text-xs font-semibold text-slate-600">{completeness}% application details complete</p></section><section className="rounded-3xl border border-emerald-200 bg-emerald-50 p-5"><ShieldCheck className="text-emerald-700" /><h2 className="mt-3 font-semibold text-emerald-950">Truth-first defaults</h2><p className="mt-1 text-sm leading-6 text-emerald-900">Legal, work-authorisation and personal answers are never guessed. If an employer asks something new, the application pauses for you.</p></section></aside>
      </div>
    </WorkspacePage>
  );
}
