import type { Metadata } from "next";
import Link from "next/link";
import { LegalCallout, LegalDocument } from "@/components/legal/LegalDocument";

export const metadata: Metadata = { title: "Billing, Cancellation and Refund Policy", description: "How optional IR35Careers paid subscriptions, renewals, cancellation and refunds work." };

const sections = [
  { id: "availability", label: "When paid plans are available" },
  { id: "charges", label: "Prices, charges and renewal" },
  { id: "cancel", label: "Cancel or change a plan" },
  { id: "refunds", label: "Cooling-off and refunds" },
  { id: "failed", label: "Failed payments and access" },
  { id: "contact", label: "Questions and complaints" },
] as const;

export default function BillingPolicyPage() {
  return <LegalDocument eyebrow="Legal & trust" title="Billing, Cancellation and Refund Policy" summary="This policy applies only when IR35Careers displays a paid plan and enables secure checkout. Until then, no paid subscription is offered and no card is requested." sections={[...sections]}>
    <section aria-labelledby="availability"><h2 id="availability">When paid plans are available</h2><p className="mt-3">A paid plan is available only when its price, billing period, included features, renewal terms, legal operator details and checkout button appear on the <Link href="/pricing">Pricing</Link>, legal pages and signed-in Billing pages. A greyed-out or provider-gated plan cannot be purchased.</p><p className="mt-3">IR35Careers does not charge per application and does not take a commission from contract earnings. Core public contract discovery remains available under the access terms shown at the time.</p></section>
    <section aria-labelledby="charges"><h2 id="charges">Prices, charges and renewal</h2><ul className="mt-4"><li>The displayed price states the billing interval and applicable VAT treatment.</li><li>Hosted Stripe Checkout repeats the amount and renewal terms before payment.</li><li>A recurring plan renews at the stated interval until cancelled.</li><li>We will not add optional products or change plan tier without your action.</li></ul><p className="mt-3">Material price changes require advance notice and will not be hidden inside application activity.</p></section>
    <section aria-labelledby="cancel"><h2 id="cancel">Cancel or change a plan</h2><p className="mt-3">Open <Link href="/billing">Plans and billing</Link> and choose Manage billing to use the payment provider&apos;s short-lived customer portal. You can cancel renewal there without contacting a salesperson. Unless the portal states otherwise, cancellation stops future renewal and paid access continues until the end of the already-paid billing period.</p><p className="mt-3">Deleting your IR35Careers account also deletes the linked Stripe customer and immediately cancels any active subscription. This can end paid access before the current period finishes, so use the billing portal when you only want to stop renewal and keep the account.</p><p className="mt-3">If the portal is unavailable, use <Link href="/contact">Contact</Link> before the renewal date. We will verify the account and process the request without requiring unnecessary personal information.</p></section>
    <section aria-labelledby="refunds"><h2 id="refunds">Cooling-off rights and refunds</h2><LegalCallout><strong>Your statutory rights are not reduced.</strong> UK online service contracts normally carry a 14-day cancellation period. If you expressly ask for service to begin during that period, any refund may be reduced to reflect service already supplied.</LegalCallout><p className="mt-3">To request cancellation or a refund, use <Link href="/contact">Contact</Link> with the account email, charge date and reason. Do not send card numbers. We assess duplicate charges, service failures, statutory cancellation rights and any plan-specific promise fairly and respond with the outcome. Approved refunds return through the original payment method; provider processing time may apply.</p><p className="mt-3">For general UK guidance, see the government&apos;s information about <a href="https://www.gov.uk/government/publications/online-dating-what-to-look-out-for/online-dating-what-to-look-out-for" target="_blank" rel="noreferrer">online subscription cancellation rights</a>.</p></section>
    <section aria-labelledby="failed"><h2 id="failed">Failed payments and access</h2><p className="mt-3">A failed payment does not trigger repeated application activity or expose CV data to the payment provider. The account is moved to a payment-review state and paid entitlements are withheld until Stripe confirms an active subscription through a signed webhook. Sandbox payments never unlock production benefits.</p><p className="mt-3">Your account-owned records remain subject to the <Link href="/privacy">Privacy Notice</Link> and account deletion controls even if a paid plan ends.</p></section>
    <section aria-labelledby="contact"><h2 id="contact">Questions and complaints</h2><p className="mt-3">Use <Link href="/contact">Contact</Link> for a billing question or complaint. Include the account email and provider receipt reference where available, but never include full payment-card details or provider secrets.</p></section>
  </LegalDocument>;
}
