import type { Metadata } from "next";
import Link from "next/link";
import { BellRing, Bot, Code2, ExternalLink, Globe2, Mail, Puzzle, Smartphone } from "lucide-react";
import { PublicFooter } from "@/components/PublicFooter";
import { PublicHeader } from "@/components/PublicHeader";

export const metadata: Metadata = { title: "Platforms", description: "Use IR35Careers on the web, as an installable app, and through the public contract-search API." };
const platforms = [
  { icon: Globe2, state: "Available", title: "Responsive web workspace", body: "Search, prepare, review and track from modern desktop, tablet and mobile browsers.", href: "/dashboard", action: "Open workspace" },
  { icon: Smartphone, state: "Available", title: "Installable mobile web app", body: "Add IR35Careers to an iPhone, iPad or Android home screen for a standalone app window and offline recovery.", href: "#install", action: "Installation steps" },
  { icon: BellRing, state: "Available", title: "Saved searches and alerts", body: "Keep focused contract searches together. Provider-backed email delivery stays labelled until connected.", href: "/alerts", action: "Manage alerts" },
  { icon: Code2, state: "Available", title: "Developer search API", body: "Use the read-only public endpoint for IR35-aware search, rate filtering and source freshness.", href: "/developers", action: "Read API docs" },
  { icon: Bot, state: "Available", title: "MCP server", body: "Connect read-only contract search, detail and public-URL analysis tools to a compatible local MCP host.", href: "/downloads/ir35careers-mcp-v1.zip", action: "Download MCP server" },
  { icon: Puzzle, state: "Developer preview", title: "Chrome job analyser", body: "A minimal-permission extension sends the active public job URL to the same safe external-role analyser. It cannot read forms or submit applications.", href: "/downloads/ir35careers-chrome-extension-v1.zip", action: "Download extension ZIP" },
  { icon: ExternalLink, state: "Safe handoff", title: "Original job websites", body: "Every indexed role retains its source. Unsupported login or CAPTCHA steps remain with the original provider.", href: "/jobs", action: "Browse contracts" },
  { icon: Mail, state: "Provider gate", title: "Recruiter email and messaging", body: "The linked inbox and classifier exist, but real forwarding, WhatsApp and SMS require approved providers and consent controls.", href: "/inbox", action: "Preview inbox" },
];

export default function PlatformsPage() {
  return <div className="min-h-screen bg-slate-50"><PublicHeader /><main className="ir35-container py-12 sm:py-16"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-brand-700">Wherever contract work happens</p><h1 className="mt-3 text-4xl font-bold tracking-[-0.04em] text-slate-950 sm:text-5xl">One contractor workspace, across every useful screen.</h1><p className="mt-5 text-base leading-7 text-slate-600">Available surfaces are usable today. Provider-dependent channels are shown with their real connection state instead of being presented as finished.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{platforms.map((item)=><article key={item.title} className="flex min-h-64 flex-col rounded-3xl border border-slate-200 bg-white p-6 shadow-card"><div className="flex items-start justify-between gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-brand-50 text-brand-700"><item.icon size={21} /></span><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${item.state === "Provider gate" ? "bg-amber-50 text-amber-800" : "bg-emerald-50 text-emerald-800"}`}>{item.state}</span></div><h2 className="mt-5 text-lg font-bold text-slate-950">{item.title}</h2><p className="mt-2 flex-1 text-sm leading-6 text-slate-600">{item.body}</p><Link href={item.href} className="ir35-focus mt-5 inline-flex min-h-10 items-center font-bold text-brand-700">{item.action} →</Link></article>)}</div>
    <section id="install" className="mt-12 scroll-mt-28 rounded-3xl border border-slate-200 bg-slate-950 p-7 text-white sm:p-10"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-300">Install the app</p><h2 className="mt-3 text-2xl font-bold">Keep IR35Careers on your home screen</h2><div className="mt-6 grid gap-6 md:grid-cols-2"><div><h3 className="font-bold">iPhone and iPad</h3><ol className="mt-3 ml-5 list-decimal space-y-2 text-sm leading-6 text-slate-300"><li>Open IR35Careers in Safari.</li><li>Choose Share, then Add to Home Screen.</li><li>Confirm the IR35Careers name and mark.</li></ol></div><div><h3 className="font-bold">Android and desktop Chrome</h3><ol className="mt-3 ml-5 list-decimal space-y-2 text-sm leading-6 text-slate-300"><li>Open the browser menu.</li><li>Choose Install app or Add to Home screen.</li><li>Open it from the new app icon.</li></ol></div></div></section>
  </main><PublicFooter /></div>;
}
