import type { Metadata } from "next";
import Link from "next/link";
import { Braces, Database, Download, ShieldCheck, TerminalSquare } from "lucide-react";
import { PublicFooter } from "@/components/PublicFooter";
import { PublicHeader } from "@/components/PublicHeader";

export const metadata: Metadata = { title: "Developer API", description: "Read-only IR35Careers contract-search API documentation." };
const params = [["q","Role, company or description search"],["location","UK town or region substring"],["ir35","outside, inside or tbc"],["remote","remote, hybrid or onsite"],["min_rate","Minimum advertised day rate"],["skills","Comma-separated canonical skills"],["within_days","1 to 60 days"],["sort","recent, rate_high or rate_low"],["page / per_page","Pagination; up to 50 per page"]];

export default function DevelopersPage() {
  return <div className="min-h-screen bg-slate-50"><PublicHeader /><main className="ir35-container py-12 sm:py-16"><div className="grid gap-10 lg:grid-cols-[0.7fr_1.3fr]"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-brand-700">Developer API</p><h1 className="mt-3 text-4xl font-bold tracking-[-0.04em] text-slate-950 sm:text-5xl">Contract search, with IR35 context.</h1><p className="mt-5 text-base leading-7 text-slate-600">The public endpoint is read-only and requires no API key for normal interactive use. It returns active indexed roles, source freshness and explicit status evidence fields.</p><div className="mt-6 space-y-3">{[[Database,"Production-shaped data"],[ShieldCheck,"No write or application scope"],[Braces,"JSON responses with cache headers"]].map(([Icon,label])=>{const Item=Icon as typeof Database; return <p key={String(label)} className="flex items-center gap-2 text-sm font-semibold text-slate-700"><Item size={17} className="text-brand-700" />{String(label)}</p>;})}</div></div><div className="rounded-3xl border border-slate-200 bg-slate-950 p-6 text-slate-100 shadow-card"><p className="text-xs font-bold uppercase tracking-[0.14em] text-emerald-300">GET</p><code className="mt-3 block overflow-x-auto whitespace-pre text-sm leading-7">https://www.ir35careers.com/api/jobs/search{`\n`}?q=react{`\n`}&amp;ir35=outside{`\n`}&amp;min_rate=600{`\n`}&amp;per_page=20</code></div></div>
    <section className="mt-12 grid gap-8 lg:grid-cols-[1fr_0.8fr]"><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white"><div className="border-b border-slate-200 px-6 py-4"><h2 className="text-xl font-bold text-slate-950">Query parameters</h2></div><dl>{params.map(([name,desc])=><div key={name} className="grid gap-1 border-b border-slate-100 px-6 py-4 last:border-0 sm:grid-cols-[150px_1fr]"><dt><code className="rounded bg-slate-100 px-2 py-1 text-sm font-bold text-brand-800">{name}</code></dt><dd className="text-sm leading-6 text-slate-600">{desc}</dd></div>)}</dl></div><aside className="rounded-3xl border border-emerald-200 bg-emerald-50 p-6"><h2 className="text-lg font-bold text-emerald-950">Responsible use</h2><ul className="mt-4 ml-5 list-disc space-y-2 text-sm leading-6 text-emerald-900"><li>Respect response cache headers and avoid repetitive polling.</li><li>Retain the original source link and IR35 evidence label.</li><li>Do not present TBC as Outside IR35.</li><li>Do not use this endpoint to submit applications.</li></ul><p className="mt-5 text-sm text-emerald-900">For higher-volume or commercial access, use <Link href="/contact" className="font-bold underline">Contact</Link> before integrating.</p></aside></section>
    <section className="mt-8 rounded-3xl border border-slate-200 bg-white p-6 sm:p-8"><div className="grid gap-6 lg:grid-cols-[0.75fr_1.25fr]"><div><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-brand-50 text-brand-700"><TerminalSquare size={21} /></span><h2 className="mt-4 text-2xl font-bold text-slate-950">Read-only command-line helper</h2><p className="mt-2 text-sm leading-6 text-slate-600">Search IR35-aware contracts or analyse a public job URL from a terminal. It uses the same public endpoints, needs no account, and has no application-submission permission.</p><a href="/downloads/ir35careers-cli.mjs" download className="ir35-focus mt-5 inline-flex min-h-11 items-center gap-2 rounded-xl bg-brand-600 px-4 text-sm font-bold text-white hover:bg-brand-700"><Download size={17} /> Download CLI helper</a></div><div className="rounded-2xl bg-slate-950 p-5 text-slate-100"><p className="text-xs font-bold uppercase tracking-[0.14em] text-emerald-300">Examples</p><code className="mt-3 block overflow-x-auto whitespace-pre text-sm leading-7">node ir35careers-cli.mjs search &quot;platform engineer&quot;{`\n`}node ir35careers-cli.mjs analyse &quot;https://example.com/job&quot;</code></div></div></section>
  </main><PublicFooter /></div>;
}
