import type { Metadata } from "next";
import Link from "next/link";
import { LegalCallout, LegalDocument } from "@/components/legal/LegalDocument";

export const metadata: Metadata = { title: "Terms of Use", description: "Terms governing use of IR35Careers job discovery and contractor workspace tools." };

const sections = [
  { id: "service", label: "The service" },
  { id: "accounts", label: "Accounts and acceptable use" },
  { id: "jobs", label: "Jobs and third-party links" },
  { id: "ir35", label: "IR35 and tax information" },
  { id: "cv-tools", label: "CV and application tools" },
  { id: "networking", label: "Networking and referrals" },
  { id: "billing", label: "Paid plans and billing" },
  { id: "availability", label: "Availability and liability" },
  { id: "ending", label: "Ending use and law" },
] as const;

export default function TermsPage() {
  return (
    <LegalDocument eyebrow="Legal & trust" title="Terms of Use" summary="These terms set fair boundaries for using IR35Careers, its job information and contractor preparation tools." sections={[...sections]}>
      <section aria-labelledby="service"><h2 id="service">The service</h2><p className="mt-3">IR35Careers provides UK contract-job discovery, educational IR35 resources and optional contractor-workspace tools. By creating an account or using the workspace, you agree to these terms and acknowledge the <Link href="/privacy">Privacy Notice</Link>.</p><p className="mt-3">You must be at least 18 years old and legally able to enter into these terms. Public job browsing does not require an account.</p></section>
      <section aria-labelledby="accounts"><h2 id="accounts">Accounts and acceptable use</h2><ul className="mt-4"><li>Provide accurate account information, protect your credentials and tell us about suspected misuse.</li><li>Use the service only for lawful contractor-search and career-preparation purposes.</li><li>Do not scrape at scale, bypass access controls, interfere with security, upload malicious content, impersonate another person or use the service to discriminate.</li><li>Do not upload confidential information you do not have permission to process.</li></ul><p className="mt-3">We may restrict access where reasonably necessary to protect users, providers or the service and will act proportionately where practical.</p></section>
      <section aria-labelledby="jobs"><h2 id="jobs">Job listings and employer systems</h2><p className="mt-3">Listings may come from employers, authorised feeds, job boards and public ATS endpoints. IR35Careers normalises and deduplicates the data but does not employ the advertiser, guarantee a vacancy or endorse a recruiter.</p><p className="mt-3">An employer or agency connecting a public careers board confirms that it is authorised to act for that organisation, that the supplied board identifier is accurate and that the verified recruitment inbox may receive candidate-approved applications for those roles. A connection can be refused, paused or removed where authority, source accuracy, applicant handling or platform safety cannot be established.</p><p className="mt-3">The original employer or ATS remains the authoritative vacancy and application destination. After your final approval, IR35Careers may use its controlled browser runner or a verified recruitment connection to enter the approved packet into the employer form. A role is marked Applied only when the employer portal returns a recognisable confirmation. Report expired, misleading or rights-infringing listings through <Link href="/contact">Contact</Link>.</p></section>
      <section aria-labelledby="ir35"><h2 id="ir35">IR35, tax and take-home information</h2><LegalCallout><strong>Educational information, not professional advice.</strong> IR35 status depends on the written terms and actual working practices of each engagement. Calculators and labels are indicative and may not reflect your circumstances.</LegalCallout><p className="mt-3">Obtain advice from a suitably qualified tax, legal or employment-status professional before relying on a status assessment, contract structure or financial estimate.</p></section>
      <section aria-labelledby="cv-tools"><h2 id="cv-tools">CV, scoring and application tools</h2><p className="mt-3">Role-match scores and suggested edits are preparation aids, not promises of applicant-tracking-system performance, interviews or work. You remain responsible for truthfulness, accuracy and the version you use. Role tailoring may use the local evidence engine or an enhanced language-model provider when configured, as explained in the <Link href="/ai-disclosure">AI and Automation Disclosure</Link>.</p><ul className="mt-4"><li>IR35Careers does not add missing experience merely because a role requests it.</li><li>You can compare, reject and edit suggested text before it changes a tailored version.</li><li>When you choose Approve and apply now, you instruct the IR35Careers server runner to complete and submit the approved materials to the employer&apos;s application system, including ordinary employer-account creation, required application terms and email-verification steps. No browser extension is required.</li><li>The runner may use your private IR35Careers application email so employer confirmations and replies can be linked to your account and forwarded to your registered email.</li><li>An employer form may pause and ask you for a new answer, identity check or security step that cannot safely be completed from your saved profile.</li><li>The runner does not bypass CAPTCHAs, access controls, identity checks or employer security measures.</li><li>A saved application is not proof of submission; only an employer-system confirmation is shown as submitted.</li><li>We use duplicate controls, but employer systems can change or fail and we cannot guarantee acceptance, consideration, an interview or work.</li><li>Do not use generated text to misrepresent qualifications, identity, work history or right to work.</li></ul></section>
      <section aria-labelledby="networking"><h2 id="networking">Networking and referral tools</h2><p className="mt-3">The Network workspace is a private preparation and record-keeping tool. It does not access a social network, discover personal details, send messages or claim that someone has agreed to refer you.</p><ul className="mt-4"><li>Add only contact information you obtained lawfully and have a legitimate reason to use.</li><li>Review every draft for accuracy, relevance and an appropriate tone before choosing an external channel.</li><li>Respect a contact&apos;s preferences, do not send bulk or repeated unsolicited messages, and delete details you no longer need.</li><li>A copied or saved draft is not proof that a message was delivered or a referral was made.</li></ul></section>
      <section aria-labelledby="billing"><h2 id="billing">Paid plans and billing</h2><p className="mt-3">No paid plan exists unless a price, currently delivered benefits and active checkout are displayed. If you choose one, Stripe processes payment and signed provider events control entitlements; a return from Checkout alone does not prove payment. Before checkout you must accept the current terms and billing policy and, when requested, expressly ask for immediate service access. Renewal, cancellation, cooling-off and refund information is in the <Link href="/billing-policy">Billing, Cancellation and Refund Policy</Link>. Statutory consumer rights are unaffected.</p></section>
      <section aria-labelledby="availability"><h2 id="availability">Availability, intellectual property and liability</h2><p className="mt-3">We aim to provide a reliable and accessible service but cannot promise uninterrupted availability or error-free third-party data. We may change or discontinue features, with reasonable notice for material account features where practical.</p><p className="mt-3">The IR35Careers brand, interface and original guidance are protected by applicable intellectual-property law. Job-advertisement rights remain with their respective owners. You retain rights in material you upload and give us the limited permission needed to process it for the features you request.</p><p className="mt-3">Nothing in these terms excludes liability that cannot lawfully be excluded. Subject to that, IR35Careers is not responsible for hiring decisions, third-party websites, indirect losses or decisions made solely from educational status labels or estimates.</p></section>
      <section aria-labelledby="ending"><h2 id="ending">Ending use, changes and governing law</h2><p className="mt-3">You can stop using the service at any time. Signed-in users can export their information and permanently delete their account in <Link href="/settings">Settings</Link>; deleting an account immediately cancels the linked Stripe customer and can end paid access before the current period finishes. If you only want to stop renewal, use Billing management instead. If you cannot sign in, use <Link href="/contact">Contact</Link> so identity can be verified. Provisions that logically continue, such as ownership, disclaimers and dispute terms, survive closure.</p><p className="mt-3">These terms are governed by the law of England and Wales, and the courts of England and Wales have jurisdiction, without removing any mandatory consumer rights that apply where you live. We will date material updates and ask account holders to accept a new version when appropriate.</p></section>
    </LegalDocument>
  );
}
